### ISSUE TITLE
Correct markdown formatting

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-bot-ui#5] opened 2019-05-21 22:31 UTC
Currently markdown rendering only work correctly within Adaptive Cards.
Ideally it should work with ordinary messages.

![image](https://user-images.githubusercontent.com/20632432/58135141-a0f16e80-7c6c-11e9-9a47-a81e8c427812.png)

**Comment by nicholasamiller** [comment] 2019-06-11 12:02
Here's a sample on how to do this from Telerik: https://dojo.telerik.com/EmOCEYAS
We should try using that approach for all activities with type 'message', as opposed to the 'md_message' in the sample.

**Comment by sitrobotsit** [comment] 2019-06-12 07:55
The only way I could get this to work with by registering a template as per their example. 
Also, a byproduct of using markdown.toHTML on the generic "message" type is that we now get <p> tags which adds extra padding to the messages. Personally I prefer this as it makes the icons feel more balanced. 
I'll do a pull request for this now.

**Comment by nicholasamiller** [comment] 2019-06-12 10:41
Thanks Luke!  
I still see two problems we need to fix.  
Firstly, the links try to open in the iFrame, and fail anyway.
![image](https://user-images.githubusercontent.com/20632432/59344394-589c0c80-8d51-11e9-815f-afdb813740fb.png)
We want them to open in a new tab.

Secondly, markdown lists are not correctly rendering:
![image](https://user-images.githubusercontent.com/20632432/59344660-e5df6100-8d51-11e9-813e-507815d70504.png)

Telerik support recommended using the Showdown markdown renderer.  

Also, I know that Markdown lists render correctly in Microsoft's BotFramework WebChat client: 
![image](https://user-images.githubusercontent.com/20632432/59344919-5b4b3180-8d52-11e9-9604-6cddaeff87f4.png)

**Comment by sitrobotsit** [comment] 2019-06-12 11:55
Good call on Showdown. It's a much better library. 
Both those issues are addressed now and merged in to master. 
I noticed the "Helpful" buttons are erroring on the Showdown library now. But they were erroring on post before so I'm sure where the issue is on that.

**Closed** 2019-06-13 23:17 UTC
Labels: P1
